apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-food-deployment
spec:
  selector:
    matchLabels:
      app: app-food-selector
  template:
    metadata:
      labels:
        app: app-food-selector
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672  # Porta padrão do RabbitMQ
            - containerPort: 15672 # Porta do painel de gerenciamento
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
          volumeMounts:
            - name: rabbitmq-config-volume
              mountPath: /etc/rabbitmq
              readOnly: true
        - name: app-food
          image: cledkube/ms-pedido:latest
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8084
          env:
            - name: DB_HOST
              value: food
            - name: URL_DB
              value: aurora-cluster-food.cluster-c1w4uwac23w1.us-east-1.rds.amazonaws.com
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-postgres-secret
                  key: password
      volumes:
        - name: postgres-storage
        - name: rabbitmq-config-volume
          emptyDir: {}
      
