apiVersion: v1
kind: Service
metadata:
  name: mongo-food-service
spec:
  selector:
    app: app-food-selector
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer
